name: Validations (testing)

on:
  pull_request_target:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.2]

    steps:
    #- name: Checkout Forecast Hub Repo
    #  uses: actions/checkout@v2
    - name: Checkout Validation Repo
      uses: actions/checkout@v2
      with:
        repository: 'reichlab/covid19-forecast-hub-validations'
        ref: 'config'
      #  path: 'covid19-forecast-hub-validations'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install python dependencies 
      run: pip3 install -r requirements.txt
      #working-directory: ./covid19-forecast-hub-validations
    - name: Validations output
    #  working-directory: ./covid19-forecast-hub-validations
      run: python main.py --project_dir ${{ github.workspace }}
      env:
        GH_TOKEN: ${{ github.token }}
